import { IFlow } from '../model/IFlow';

/**
 * CodeExecutor - Executes AI-generated TypeScript to produce IFlow instances
 *
 * This class bridges the AI Frontend and Compiler Backend by executing
 * the TypeScript code generated by the AI and returning the IFlow object
 * that the compiler expects.
 *
 * Execution Strategy:
 * - Uses eval() with proper context (has access to SDK classes)
 * - Validates that result is an IFlow instance
 * - Returns IFlow ready for compiler
 *
 * Security Note:
 * - Only executes code that has passed FlowValidator
 * - Code comes from controlled AI generation, not arbitrary user input
 * - Eval is acceptable in this controlled environment
 *
 * Alternative approaches considered:
 * - ts-node (requires TypeScript compilation - slower)
 * - vm.runInNewContext (Node.js VM - more complex)
 * - Writing to file and importing (filesystem overhead)
 *
 * eval() is fastest and simplest for this use case.
 */
export class CodeExecutor {
    /**
     * Executes TypeScript code and returns the IFlow instance
     *
     * The generated code must:
     * - Use SAP Integration SDK classes (IFlow, Component)
     * - Export default flow
     *
     * @param code - Validated TypeScript code from AI
     * @returns IFlow instance ready for compiler
     * @throws Error if execution fails or result is not an IFlow
     *
     * @example
     * const code = `
     *   const flow = new IFlow("MyFlow");
     *   const modifier = new Component("CallActivity_1", "Set Body", "Enricher");
     *   modifier.properties.bodyType = "constant";
     *   modifier.properties.body = "Hello";
     *   flow.addComponent(modifier);
     *   export default flow;
     * `;
     * const executor = new CodeExecutor();
     * const flow = executor.execute(code);
     * // flow is IFlow instance
     */
    execute(code: string): IFlow {
        try {
            // Import SDK classes into execution context
            const { IFlow } = require('../model/IFlow');
            const { Component } = require('../model/Component');
            const { Connection } = require('../model/Connection');

            // Create execution context with SDK classes
            const context = {
                IFlow,
                Component,
                Connection,
                exports: {} as any
            };

            // Replace "export default" with "exports.default ="
            // This allows eval to work with ES module syntax
            const executableCode = code
                .replace(/export\s+default\s+/g, 'exports.default = ')
                .replace(/export\s+default/g, 'exports.default =');

            // Execute code in context
            const execute = new Function(
                'IFlow',
                'Component',
                'Connection',
                'exports',
                executableCode + '; return exports.default;'
            );

            const result = execute(
                context.IFlow,
                context.Component,
                context.Connection,
                context.exports
            );

            // Validate result is an IFlow instance
            if (!result || !(result instanceof IFlow)) {
                throw new Error(
                    'Code execution did not produce an IFlow instance. ' +
                    'Ensure code exports default flow.'
                );
            }

            return result;

        } catch (error) {
            if (error instanceof Error) {
                throw new Error(
                    `Code execution failed: ${error.message}\n` +
                    `Generated code may have syntax errors or missing exports.`
                );
            }
            throw new Error('Code execution failed with unknown error');
        }
    }
}
