/**
 * SupportedComponents - Canonical registry of supported compiler components
 *
 * This is the SINGLE SOURCE OF TRUTH for which components are supported
 * by the compiler (v1.0) and can be generated by the AI.
 *
 * When new components are added to the compiler, they MUST be added here.
 * PromptBuilder dynamically generates documentation from this list.
 *
 * Version 1.0: Only Content Modifier (Enricher)
 * Version 1.2: Will add Router, Groovy, Data Store, etc.
 */

/**
 * Component definition for AI generation
 */
export interface ComponentDefinition {
    /**
     * Component type identifier used in SDK
     * e.g., "Enricher"
     */
    type: string;

    /**
     * Human-readable name
     * e.g., "Content Modifier"
     */
    displayName: string;

    /**
     * Description of what the component does
     */
    description: string;

    /**
     * Required properties for this component type
     */
    requiredProperties: PropertyDefinition[];

    /**
     * Example usage in TypeScript
     */
    example: string;
}

/**
 * Property definition
 */
export interface PropertyDefinition {
    name: string;
    type: string;
    description: string;
    exampleValue?: string;
}

/**
 * Supported components in Version 1.0
 *
 * IMPORTANT: When adding components, ensure they are supported by the compiler.
 * The AI will generate code using these components.
 */
export const SupportedComponents: ComponentDefinition[] = [
    {
        type: 'Enricher',
        displayName: 'Content Modifier',
        description: 'Modifies message body, headers, or properties during flow execution',
        requiredProperties: [
            {
                name: 'bodyType',
                type: 'string',
                description: 'Type of body modification',
                exampleValue: 'constant'
            },
            {
                name: 'body',
                type: 'string',
                description: 'Message body content',
                exampleValue: 'Hello from SAP Integration Suite!'
            }
        ],
        example: `const modifier = new Component("CallActivity_1", "Set Body", "Enricher");
modifier.properties.bodyType = "constant";
modifier.properties.body = "Hello from SAP Integration Suite!";
flow.addComponent(modifier);`
    }
];

/**
 * Get list of supported component types
 */
export function getSupportedComponentTypes(): string[] {
    return SupportedComponents.map(c => c.type);
}

/**
 * Get component definition by type
 */
export function getComponentDefinition(type: string): ComponentDefinition | undefined {
    return SupportedComponents.find(c => c.type === type);
}
